{% set version = "1.5.1" %}
{% set gh_org = "audreyr" %}
{% set name = "cookiecutter" %}
{% set sha256 = "3fcb10dbfe4da02bf779a88f96109c1a28ff68f42d87587788f841735820249c" %}


package:
  name: {{ name }}
  version: {{ version }}

source:
  fn: {{ name }}-{{ version }}.tar.gz
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: {{ sha256 }}

build:
  number: 0
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - cookiecutter = cookiecutter.cli:main

requirements:
  build:
    - python
    - setuptools
  run:
    - binaryornot >=0.2.0
    - click >=5.0
    - future >=0.15.2
    - jinja2 >=2.7
    - jinja2-time >=0.1.0
    - poyo >=0.1.0
    - python
    - whichcraft >=0.4.0

test:
  requires:
    - freezegun
    - git
    - pytest
    - pytest-catchlog
    - pytest-cov
    - pytest-mock
    - python
    - mercurial  # [py2k]
  source_files:
    - tests
  commands:
    - cookiecutter --version
    - cookiecutter --help
    - py.test --cov=cookiecutter -k "not test_make_sure_path_exists and not pypackage_git"

about:
  home: https://github.com/{{ gh_org }}/{{ name }}
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  summary: >
            A command-line utility that creates projects from cookiecutters
            (project templates). E.g. Python package projects, jQuery plugin
            projects.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
