{% set version = "1.7.2" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: efb6b2d4780feda8908a873e38f0e61778c23f6a2ea58215723bcceb5b515dac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cookiecutter = cookiecutter.cli:main

requirements:
  host:
    - pip
    - python
  run:
    - binaryornot >=0.4.4
    - click >=7.0
    - jinja2 <3.0.0a0
    - jinja2-time >=0.2.0
    - markupsafe <2.0.0
    - poyo >=0.5.0
    - python
    - python-slugify >=4.0.0
    - requests >=2.23.0
    - six >=1.10
    - whichcraft >=0.4.0

test:
  requires:
    - freezegun
    - git
    # Omit to avoid falling back to Python 2.7
    #- mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-cov
    - pytest-mock
    - python 3.*
  source_files:
    - tests
  commands:
    #- python -m pip check
    - cookiecutter --version
    - cookiecutter --help
    # Skip 'make_sure_path_exists' because it does not fail when running the
    # `conda build` as root (e.g., inside our build containers)
    - py.test --cov=cookiecutter -v -k 'not make_sure_path_exists'

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/master/docs
  summary: >
    A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
