{% set name = "cookiecutter" %}
{% set version = "2.5.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: e61e9034748e3f41b8bd2c11f00d030784b48711c4d5c42363c50989a65331ec

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv
  entry_points:
    - cookiecutter = cookiecutter.cli:main

requirements:
  host:
    - pip
    - python
    - setuptools
    - wheel
  run:
    - python
    - arrow
    - binaryornot >=0.4.4
    - click >=7.0,<9.0.0
    - jinja2 >=2.7,<4.0.0
    - python-slugify >=4.0.0
    - pyyaml >=5.3.1
    - requests >=2.23.0
    - rich

test:
  imports:
    - cookiecutter
    - cookiecutter.main
    - cookiecutter.environment
    - cookiecutter.exceptions
  requires:
    - freezegun
    - git
    - m2-grep  # [win]
    # omit mercurial, because it's not available and optional
    # - mercurial  # [not (win and py3k)]
    - pip
    - pytest
    - pytest-mock
    - python
  source_files:
    - tests
  commands:
    - pip check
    - cookiecutter --version
    - cookiecutter --version | grep -iE "Cookiecutter {{ version.replace(".", "\\.") }}"
    - pip list
    - pip list | grep -iE "cookiecutter\s+{{ version.replace(".", "\\.") }}"
    - cookiecutter --help
    - pytest tests -vv

about:
  home: https://github.com/cookiecutter/cookiecutter
  license: BSD-3-Clause
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/cookiecutter/cookiecutter
  doc_url: https://cookiecutter.readthedocs.io
  summary: >
    A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.
  description: |
    Cookiecutter takes a template provided as a directory structure with template-files. Templates can be located in the filesystem, as a ZIP-file or on a VCS-Server (Git/Hg) like GitHub.
    It reads a settings file and prompts the user interactively whether or not to change the settings.
    Then it takes both and generates an output directory structure from it.
    Additionally the template can provide code (Python or shell-script) to be executed before and after generation (pre-gen- and post-gen-hooks).
extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
