{% set version = "1.7.2" %}

package:
  name: cookiecutter
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/cookiecutter/cookiecutter-{{ version }}.tar.gz
  sha256: efb6b2d4780feda8908a873e38f0e61778c23f6a2ea58215723bcceb5b515dac

build:
  noarch: python
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv
  entry_points:
    - cookiecutter = cookiecutter.cli:main

requirements:
  host:
    - pip
    - python
  run:
    - binaryornot >=0.2.0
    - click >=7.0
    - future >=0.15.2
    - jinja2 >=2.7
    - jinja2-time >=0.1.0
    - poyo >=0.1.0
    - python
    - requests >=2.18.0
    - whichcraft >=0.4.0

test:
  requires:
    - freezegun
    - git
    - mercurial  # [py2k]
    - pytest
    - pytest-catchlog
    - pytest-cov
    - pytest-mock
    - python
  source_files:
    - tests
  commands:
    - cookiecutter --version
    - cookiecutter --help
    - py.test --cov=cookiecutter

about:
  home: https://github.com/cookiecutter/cookiecutter
  license_family: BSD
  license_file: LICENSE
  license: BSD-3-Clause
  doc_url: https://cookiecutter.readthedocs.io
  doc_source_url: https://github.com/cookiecutter/cookiecutter/tree/master/docs
  summary: >
    A command-line utility that creates projects from cookiecutters (project templates), e.g. creating a Python package project from a Python package project template.

extra:
  recipe-maintainers:
    - bollwyvl
    - cadair
    - jakirkham
    - pydanny
