travis:
  secure:
    BINSTAR_TOKEN: GyHghDINTZ4GGY0x4K2ZvmGovR2XWMN2VfbDFCWK1xhIAlsPvmbB58QpVuO8bU+Q/6fYoWgfFcY6bnCJiZw9vdmiprvQlYBgLN9j4SOvkDOabejVyGhLG8JOosoZzHN8hAS2W+u3TO061BFUeSdXBr2N0L+qjdRThzi6xKs/dxnlozMfhu7Nto4I3DNaXUrJBxDmGLShO0UdwcEuxxXQRRgrmAxsP8U4gr99FSI28QQPUk1HmdfL21ndbU78acRkkpZ7eOByXh1BfS1h2XaFzc/HqWQxSjl/+5NRFWZlLvDdbpvC69T235NGmG7GvHPrwBzRVLvVOs+gUPr/gxEzg8H+yrcWmBSIX1Oiq/BZ6INJvrZCF7QgDn5U34eG5OIYqROWgKBcjaflS7kf/P3V0dARPlJ/Q4u0e1BCo45YLnpTOjnwA7zr9RjjeWBOZ9vn15Rf6qjic9alt3TW1shfUDt1UbManQEChf2CDg4IKB58R/3c9YKWGub4wXhZBu1Xw/Gmayje/g6+L24figoUsBL/SuSFJCOERnR/qXYd4rRj2mRINta7a4Z/LBo5DXprSDtoip5KD/NI1wvjNU8EW30ZjvaVTeZKSCLkFAU3BLXmyo91qYHsjaLjUQglGn8z4A1HhVfx+Nqsx4fuQ2ZY7wjMFMPI36nJRhNBF4BQM4c=
appveyor:
  secure:
    BINSTAR_TOKEN: ipv/06DzgA7pzz2CIAtbPxZSsphDtF+JFyoWRnXkn3O8j7oRe3rzqj3LOoq2DZp4
