travis:
  secure:
    BINSTAR_TOKEN: Ds5Q9PuuvUPzqrpNu0fckYDOCsD2BrrvihQajqObxTv9EmoyNIdFXpFFjGawGDpeoMKoQn7R+h5uq1+G8+F09s9MbYyTQaCd6Z67izOkazHlzu5TywOR2B0+YLfvW5RYJ9aEguoi5qfSZdNVVv+rcGpsAwfyUxJSO5oar8PHrWvqGt2xKG7zq7lIn9Oc+wYxgzsodbiIDakL664M22fT+oYUUkXYW2GKzUj/cq1nvGl6xY4ncStAslMhTmUriv6nMUlxYFkonjc8uhpYZgFOEgRGIRVXsNtqBDbJ7EMph7qLK2PcvpcBojOL+j0IDBvtSmAH4b2NGA7/ZqVi2zUA5OFT93EFsN8RV8VZXSmZ1tVV3fdUH//1oxrfEHBFqHSHnhiBk3EyW6OS76TU4+ioql2/ObTpJmoITEXtgcJayNAR93pLU7IOSRcMkuHCaFPn1zzsCfy7l+amtW7aZ/u8j55CxV7d3H6nWiqNpw2Scvk3x2t+LviJyZMvYYfdzNgfj6iqjMFmulW4ZpE43BjtIfE/bnXisyt8WGaGFHkj2oxjeNsTofYHPMy9+Gyhff80/jzYQmbSZLvL0RLLDCeN/abT2VkD5wtlSg+jF2Ss1kx0N7cPViI/9cEAvYr7eBc7yKIOJMqCFJ3hHiqbawgEjyKF/YD8FP8Qy14OI/X3Tnw=
appveyor:
  secure:
    BINSTAR_TOKEN: MP4hZYylDyUWEsrt3u3cod2sbFeRwUziH02mvQOdbjsTO/l1yIxDkP/76rSIjcGC
